### ISSUE TITLE
Metabolic subsetting

### ISSUE THREAD

**Issue by yuey11** [pwwang/immunopipe#1]
error when the Metabolic module configuration is not provided.
```
    FILTERS["toml_dumps"](mf_config.subsetting)
AttributeError: 'str' object has no attribute 'subsetting'
```

**Comment by pwwang** [comment]
This is not a but we followed the wrong doc.

There is how we should compose our `config.toml`:

https://pwwang.github.io/immunopipe/markers-finder/

The example here should be updated:

https://pwwang.github.io/immunopipe/configurations/
