### ISSUE TITLE
Could U provide the pdf version of the workflow picture？

### ISSUE THREAD

**Issue by chemy-cm** [pwwang/immunopipe#4]
https://github.com/pwwang/immunopipe/raw/dev/docs/immunopipe.flowchart.png?raw=true
I want this high resolution picture to show. 
Many thanks!

**Comment by pwwang** [comment]
A pdf version is provided here:

https://github.com/pwwang/immunopipe/blob/dev/docs/immunopipe.flowchart.pdf

May I ask what you are using it for?

**Comment by chemy-cm** [comment]
I want to post in my notebook. I think the pic is very beautiful.

**Comment by pwwang** [comment]
Sure, you are very welcome to use it. It would be so much appreciated if you could also leave a link to this repo together with the figure.
